### ISSUE TITLE
When ethernet is unplugged don't display information in wired view

### ISSUE THREAD

**Issue by worldofpeace** [elementary/switchboard-plug-network#149]
![screenshot from 2019-01-24 11 22 33](https://user-images.githubusercontent.com/28888242/51692193-69c6c580-1fca-11e9-98ae-e55326583c5a.png)

Because this is unplugged there's never going to be information to populate this with and the switch isn't going to effect the physical state.
This should probably just show some text asking to connect an ethernet cable.

**Comment by peteruithoven** [comment]
I'd like to disagree. 
On my laptop, without build in ethernet port), this Wired option only shows up when I plug in a usb to ethernet adapter. Seeing the status of that Wired hardware is interesting, it can tells me for example whether there is something wrong with the cable for example. 

I do think that the contents of the Wired page could be improved in this case.

**Comment by pokgak** [comment]
Aside from displaying the hardware status, I think the toggle switch should also be disabled when there is no device to connect to or when there is no ethernet hardware present.

**Comment by psukys** [comment]
> Aside from displaying the hardware status, I think the toggle switch should also be disabled when there is no device to connect to or when there is no ethernet hardware present.

why?

**Comment by pokgak** [comment]
Forgot to include picture in my last comment. Here it is:
![image](https://user-images.githubusercontent.com/20373062/52544870-864a6680-2dee-11e9-91ed-e108df7a2c2b.png)

Connected using wifi and no ethernet cable connected. A bit confusing to me that I still can toggle ethernet on and it shows "unknown" as IP, as if I somehow screwed my configuration.

**Comment by worldofpeace** [comment]
Yeah this is what I meant by "make the switch insensitive"

**Comment by NathanBnm** [comment]
I still have this issue. There is an inconsistency between the switchboard plug and the wingpanel indicator.

I mean in the wingpanel indicator the "Wired" option is disabled, and cannot be activated as long as no ethernet cable is connected.

But in the switchboard plug the "Wired" option is always enabled, even if no ethernet cable is connected. Which is useless because it's displaying an "unknown" status.

In addition to that when you disable the "Wired" option in the switchboard plug and close the settings, it re-enables itself. So it can't be disabled.

I think the "Wired" view should adopt the same behavior than the wingpanel indicator mentionned above.

See the screenshots:

In the wingpanel indicator:

![image](https://user-images.githubusercontent.com/45366162/68541395-21349900-039f-11ea-925d-e19ae2792e04.png)

In the switchboard plug:

![image](https://user-images.githubusercontent.com/45366162/68541386-fe09e980-039e-11ea-9d7e-683ee003af97.png)

**Comment by Dirli** [comment]
I suggested a fix, but it went unnoticed. Who needs to fix this (although it does not affect the functionality), here is the patch.

https://github.com/Dirli/gpde/blob/master/pantheon-base/switchboard-plug-network/files/2.3.0-fix_unplugged_cable.patch
