### ISSUE TITLE
 Randomly the wi-fi starts off

### ISSUE THREAD

**Issue by wandertorres** [elementary/switchboard-plug-network#156]
Sometimes, on my Lenovo Ideapad 310, the system starts up with the wireless network disabled, without being able to activate, and it is necessary to disconnect and reconnect in order to return to normal

**Comment by peteruithoven** [comment]
Please translate, the language we use on github is English.

**Comment by wandertorres** [comment]
> Por favor, traduza, o idioma que usamos no github é o inglês.


Thank you for the information.

**Comment by wandertorres** [comment]
> Please translate, the language we use on github is English.

Thank you for the information.

**Comment by wandertorres** [comment]
I believe that somehow this may be related to the use of external monitor, since it usually happens when I'm connected.

**Comment by peteruithoven** [comment]
I believe these type of issues stem from layers like drivers, which we thankfully inherit from Ubuntu. I'd suggest searching online whether other people experience this issue with your network card etc when using for example Ubuntu. You could also have a look on the elementary OS StackExchange and Reddit. 
I'm closing this issue because I don't believe the network settings could be responsible for the issue you are describing.
