### ISSUE TITLE
Feature Request: Integrate popular VPN clients into the VPN section of the wingpanel and the Network Manager GUI

### ISSUE THREAD

**Issue by CodingSpiderFox** [elementary/switchboard-plug-network#337]
### Problem

There are some very popular public VPN Providers which I want to make easy use of.

N*rdVPN and P*****eInternetaccess are just two examples

### Proposal

What I would like to have:
Once I installed the official VPN provider's client application to my system and logged in to my user account at the VPN provider, I want the connection to appear in the lists of wingpanel and Network Manager GUI so I can enable them with a single click.

Otherwise I would have to always first bring up the VPN client which is not very intuitive.
For example of you go on a train's WIFI, then you have to go to the WIFI list in wingpanel usually to click the WIFI network you want to join.
Next click could then already be the VPN item in the same, already open popup and boom - all set up :)

**Comment by danirabbit** [comment]
I don't think there's really anything we can do about this. Those clients would have to use NetworkManager for our network settings to be aware of them. NordVPN, Proton, etc do offer OpenVPN files and Wireguard configuration files that are supported by NetworkManager and can be managed already here in System Settings.

Closing as "Out of scope" since we can't force 3rd party clients to use the system APIs
