### ISSUE TITLE
An better start apps menu...

### ISSUE THREAD

**Issue by LinkfandosYT** [elementary/switchboard-plug-network#351]
### Problem

Bad start menu ... Kinda ugly (sorry but its not very usefull to use...)

### Proposal

You should be able to create your start menu!!!
yeah i know im an `genius

Starting by change the order, the placement, if it shows an list or grid...
also add some quick settings... I think you see what i mean.

### Prior Art (Optional)

I have heard of alacata or something...

**Comment by danirabbit** [comment]
Hey thanks for your issue report, as it is this isn't really an actionable report with a specific problem to solve. It also sounds like maybe this is about the Applications menu and not network settings?

If so, you can change the applications menu to be in a list layout by clicking the "View by Category" button in the top left corner.

If not, please try opening a discussion post instead if you'd like to open a brainstorming post: https://github.com/elementary/applications-menu/discussions

Closing as "Not planned" since there isn't anything actionable reported here
